---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Tay Nash, Steven Carswell, and Nereus"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 1 write code to load File 1 data here:
mismanaged.plastic.waster.per.capita <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")
glimpse(mismanaged.plastic.waster.per.capita)

# Member 2 write code to load File 2 data here:
per.capita.ocean.plastic.waste <- read_csv2("data/per-capita-ocean-plastic-waste.txt")
glimpse(per.capita.ocean.plastic.waste)


# Member 3 write code to load File 3 data here:
UN.country.population <- read_tsv("data/UN_country_population.tsv")
glimpse(UN.country.population)


# Member 4 write code to load File 4 data here:
un.country.region <- read_xlsx("data/UN_country_region.xlsx")
glimpse(un.country.region)


```



```{r join-data, message = FALSE}
# Member 1 write code to create object 'plastic_data_all':
plastic_data_all <- mismanaged.plastic.waster.per.capita



# Member 2 write code to join your data to 'plastic_data_all':
plastic_data_all <- per.capita.ocean.plastic.waste %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")


# Member 3 write code to join your data to 'plastic_data_all':
plastic_data_all <- UN.country.population %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


# Member 4 write code to join your data to 'plastic_data_all':
plastic_data_all <- un.country.region %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


```


```{r print-data, message = FALSE}
# Member 1 adds code here to view the first 10 rows of 'plastic_data_all'

plastic_data_all %>% head(n=10)

```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1



```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
